# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: itVincent的博客 
subtitle: http://www.itvincent.info/
description: Android,Java,Hexo
author: Vincent Zhong
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.itvincent.info/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page
index_generator:
  per_page: 15
archive_generator:
  per_page: 20
  yearly: true
  monthly: true
tag_generator:
  per_page: 10

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    coding: git@git.coding.net:itvincent/itvincent.git
    github: https://github.com/itvincent-git/itvincent-git.github.io.git    
  branch: master

# Next Config
baidu_site_verification: yqiPTn7Wmi
avatar: http://ojicajn2x.bkt.clouddn.com/17-2-2/7850663-file_1486008757103_5b69.jpg
duoshuo_shortname: itvincent-git
baidu_analytics: 99a8f49fff6295f24c353dc89eb361e9
google_analytics: UA-91457181-1
tencent_analytics: 60548171
search:
  path: 
#  field: post
#  format: html
#  limit: 10000
# 多说热评文章 true 或者 false
duoshuo_hotartical: true
algolia:
  applicationID: 0C3UC3NIPB
  apiKey: 1fbb8c62696599536b818317fc2ea6bc
  adminApiKey: b35ece2fa3763fb9a8a3078a9693b1b6
  indexName: www.itvincent.info
  chunkSize: 5000

# 增加nofollow到外链
nofollow:
    enable: true
    exclude:

# hexo-all-minifier
html_minifier:
  enable: true
  exclude:
css_minifier:
  enable: true
  exclude: 
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false       